name: 'inception'

# Most used version of docker-compose.
version: '3.0'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    build:
      context: ./requirements/nginx
      args:
        # Use "DOMAIN_NAME" variable from .env file as "domain_name" ARG when
        # building image.
        # Possibles issues with this method here:
        # https://docs.docker.com/compose/environment-variables/envvars-precedence/
        domain_name: ${DOMAIN_NAME}
    # Expose port 443 of the container to the port 443 of the host machine.
    ports:
      - '443:443'
    # Volumes allow containers to share a persistant directory that can also be
    # accessed from host machine.
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - bridge_net
    # Always restart the container if it crash or stops for whatever reason.
    # 'on-failure' will be more suitable for a container that execute a process
    # that should terminate at a given time. Here we want our website to be
    # available 100% of the time.
    restart: always
    # Launch the container with Tini as PID 1.
    # See https://github.com/krallin/tini
    init: true
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - bridge_net
    expose:
      - 9000
    restart: always
    init: true
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/lib/mysql
    networks:
      - bridge_net
    expose:
      - 3306
    restart: always
    init: true

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/ple-stra/data/wp_files
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ple-stra/data/wp_data
      o: bind

networks:
  bridge_net:
    driver: bridge
